### ISSUE TITLE
Change startup colour

### ISSUE THREAD

**Issue by FelixNudrec** [phenze/rpi_wordclock#4]
Hej all,

I'm not able to change the startup colour. 
I tried to change it in the wordclock_display.py 
<img width="474" alt="wordclock_display" src="https://user-images.githubusercontent.com/62222775/147752981-56832e9f-c18e-4e86-a07e-1da34bda0a55.png">
and in the wordclock_config (I did it with _ and - but it's no differenz)
<img width="459" alt="wordclock_config" src="https://user-images.githubusercontent.com/62222775/147753013-f88136fe-0364-4155-a916-77318f062070.png">

I hope there is an easy solution because after today I can only access to the clock with TeamViewer because the clock is at my parents house.

Thanks for help.
Felix

PS.: Thank you for converting the whole project to Python 3

**Comment by phenze** [comment]
You are using the wrong branch.

You have to switch to development branch.

Try using Bernds development Branch because there are the latest changes included.
https://github.com/bk1285/rpi_wordclock/tree/develop
